name: flutter_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  geolocator: ^11.0.0
  persistent_bottom_nav_bar: ^5.0.2
  animated_notch_bottom_bar: ^1.0.3

dev_dependencies: 
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/


